---
title: "data-wrangling"
author: "Maya Sollen-Norrlin"
date: "2022-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading libraries   
```{r}

library(tidyverse)
library(gridExtra)
library(ggpubr)
```



```{r}

chem_data <- read.csv("chemistry-data-raw.csv", na.strings = c(""))

```

 

```{r}

str(chem_data)


```



```{r}

chem_data <- chem_data %>%
  mutate_at(c("NO3..mg.kg.", "NO2..mg.kg.", "K..mg.kg."), as.numeric)

```
```{r}
head(chem_data)

```




```{r}

chem_data$Time..weeks. <- as.factor(chem_data$Time..weeks.)

```

```{r}

str(chem_data)

```


```{r}

chem_data_filtered <- chem_data %>%
  select(Sample.ID, moisture...., pH:Time..weeks.)

str(chem_data_filtered)
```



```{r}
head(chem_data_filtered, 20)
```


```{r}

complete.cases(chem_data_filtered)

```



```{r}


chem_data_filtered[!complete.cases(chem_data_filtered),]


```



Removing rows with NA's
```{r}

chem_data_filtered <- chem_data_filtered %>%
  drop_na()

head(chem_data_filtered,20)

```

```{r}

tail(chem_data_filtered, 20)

```

Checking that all NA's are gone.
```{r}


chem_data_filtered[!complete.cases(chem_data_filtered),]


```

Renaming columns so they're easier to write.
```{r}

str(chem_data_filtered)

```

```{r}
chem_data_filtered<- chem_data_filtered %>% 
  rename(
   "NH4 (mg/kg)" = NH4..mg.kg.,
   "TON (mg/kg)" = TON..mg.kg.,
   "K (mg/kg)" = K..mg.kg.,
   "NO2 (mg/kg)" = NO2..mg.kg.,
   "NO3 (mg/kg)" = NO3..mg.kg.,
   "Conductivity (mV)" = conductivity..mV.,
   "Moisture (%)" = moisture....,
   "Weeks" = Time..weeks.
  )

head(chem_data_filtered)


```

Creating a "Fresh" category for the time stamp 0 samples (e.g. the control).
```{r}
# not sure if this is necessary, ignoring for now
#chem_data$Treatment[chem_data$weeks == 0] <- "Fresh"

#head(chem_data, 20)

```

```{r}

tail(chem_data_filtered, 20)

```

replacing negative values in the moisture and nitrate columns with 0. 
```{r}

chem_data_filtered <- chem_data_filtered%>% 
  mutate(across(c(`Moisture (%)`, `NO3 (mg/kg)`:`TON (mg/kg)`), ~ ifelse(.x<0, 0, .x)))


tail(chem_data_filtered, 20)
```


```{r}

write_csv(chem_data_filtered, "chemistry-data-tidy.csv", col_names = TRUE)

```



